name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Registry
      uses: MirzaMerdovic/Publish-Docker-Github-Action@master
      with:
        name: mirzamerdovic/unicorn
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./src/Dockerfile
        context: ./src
        semver: 1.0.0
