name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Registry
      #uses: mirzamerdovic/github-action-docker-semver@master
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: unicorn:1.0.1
        username: mirzamerdovic
        password: MiMer1984
        #semver_tag: 1.0.1-p1
        #registry: https://index.docker.io/v1/
        dockerfile: ./src/unicorn/Dockerfile
